name: Update git.md Daily

on:
  schedule:
      - cron: '0 21 * * *' # Runs daily at 12:00 AM Turkey Time (TRT)
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update git.md
      run: |
        # Example change to git.md
        echo "Last updated on $(date)" >> git.md
        
    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "arvinsoheili"
        git config user.email "soheiliarvin@gmail.com"
        git add git.md
        git commit -m "Automated daily update to git.md: $(date)"
        git push
